#!/usr/bin/env bash
set -euo pipefail

# Resolve latest versions for all container runtime components
# and write them to versions.env

get_latest_tag() {
    local repo="$1"
    gh api "repos/${repo}/releases/latest" --jq '.tag_name'
}

get_file_content() {
    local repo="$1" ref="$2" path="$3"
    gh api "repos/${repo}/contents/${path}?ref=${ref}" --jq '.content' | base64 -d
}

# --- Main release tags ---

echo "==> Fetching latest release tags..."

DOCKER_VERSION=$(get_latest_tag "moby/moby")
DOCKER_VERSION="${DOCKER_VERSION#docker-}"
PODMAN_VERSION=$(get_latest_tag "containers/podman")
COMPOSE_VERSION=$(get_latest_tag "docker/compose")

echo "  Docker:  ${DOCKER_VERSION}"
echo "  Podman:  ${PODMAN_VERSION}"
echo "  Compose: ${COMPOSE_VERSION}"

# --- Docker dependency versions from moby/moby source ---

echo "==> Deriving Docker dependency versions..."

MOBY_DOCKERFILE=$(get_file_content "moby/moby" "docker-${DOCKER_VERSION}" "Dockerfile")

CONTAINERD_VERSION=$(echo "$MOBY_DOCKERFILE" | sed -n 's/.*CONTAINERD_VERSION=\([^ ]*\).*/\1/p' | head -1)
if [[ -z "$CONTAINERD_VERSION" ]]; then
    CONTAINERD_VERSION=$(get_latest_tag "containerd/containerd")
fi

RUNC_VERSION=$(echo "$MOBY_DOCKERFILE" | sed -n 's/.*RUNC_VERSION=\([^ ]*\).*/\1/p' | head -1)
if [[ -z "$RUNC_VERSION" ]]; then
    RUNC_VERSION=$(get_latest_tag "opencontainers/runc")
fi

TINI_VERSION=$(echo "$MOBY_DOCKERFILE" | sed -n 's/.*TINI_VERSION=\([^ ]*\).*/\1/p' | head -1)
if [[ -z "$TINI_VERSION" ]]; then
    TINI_VERSION=$(get_latest_tag "krallin/tini")
fi

ROOTLESSKIT_VERSION=$(echo "$MOBY_DOCKERFILE" | sed -n 's/.*ROOTLESSKIT_VERSION=\([^ ]*\).*/\1/p' | head -1)
if [[ -z "$ROOTLESSKIT_VERSION" ]]; then
    ROOTLESSKIT_VERSION=$(get_latest_tag "rootless-containers/rootlesskit")
fi

echo "  containerd:  ${CONTAINERD_VERSION}"
echo "  runc:        ${RUNC_VERSION}"
echo "  tini:        ${TINI_VERSION}"
echo "  rootlesskit: ${ROOTLESSKIT_VERSION}"

# --- Podman dependency versions ---

echo "==> Deriving Podman dependency versions..."

CRUN_VERSION=$(get_latest_tag "containers/crun")
CONMON_VERSION=$(get_latest_tag "containers/conmon")
NETAVARK_VERSION=$(get_latest_tag "containers/netavark")
AARDVARK_DNS_VERSION=$(get_latest_tag "containers/aardvark-dns")
SLIRP4NETNS_VERSION=$(get_latest_tag "rootless-containers/slirp4netns")
FUSE_OVERLAYFS_VERSION=$(get_latest_tag "containers/fuse-overlayfs")

echo "  crun:            ${CRUN_VERSION}"
echo "  conmon:          ${CONMON_VERSION}"
echo "  netavark:        ${NETAVARK_VERSION}"
echo "  aardvark-dns:    ${AARDVARK_DNS_VERSION}"
echo "  slirp4netns:     ${SLIRP4NETNS_VERSION}"
echo "  fuse-overlayfs:  ${FUSE_OVERLAYFS_VERSION}"

# --- Write versions.env ---

echo "==> Writing versions.env..."

cat > versions.env <<EOF
# Auto-generated by versions.yml — can be manually overridden

# Docker
DOCKER_VERSION=${DOCKER_VERSION}
CONTAINERD_VERSION=${CONTAINERD_VERSION}
RUNC_VERSION=${RUNC_VERSION}
TINI_VERSION=${TINI_VERSION}
ROOTLESSKIT_VERSION=${ROOTLESSKIT_VERSION}

# Compose
COMPOSE_VERSION=${COMPOSE_VERSION}

# Podman
PODMAN_VERSION=${PODMAN_VERSION}
CRUN_VERSION=${CRUN_VERSION}
CONMON_VERSION=${CONMON_VERSION}
NETAVARK_VERSION=${NETAVARK_VERSION}
AARDVARK_DNS_VERSION=${AARDVARK_DNS_VERSION}
SLIRP4NETNS_VERSION=${SLIRP4NETNS_VERSION}
FUSE_OVERLAYFS_VERSION=${FUSE_OVERLAYFS_VERSION}
EOF

echo "==> Done"
